name: Acquire activation file 
on: 
  workflow_dispatch
jobs: 
  activation: 
    name: Request manual activation file 
    runs-on: ubuntu-latest 
    steps: 
      # Request manual activation file 
      - name: Unity - Activate
        uses: game-ci/unity-activate@v2.0.0
      
      # Upload artifact (Unity_v20XX.X.XXXX.alf) 
      - name: Expose as artifact 
        uses: actions/upload-artifact@v2 
        with: 
          name: ${{ steps.getManual LicenseFile.outputs.filePath }} 
          path: ${{ steps.getManual License File.outputs.filePath }}