name: first_workflow
on: workflow_dispatch
jobs: 
  firstjob: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Print Greetings
        run: echo "Hello World" 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Unity - Builder
        uses: game-ci/unity-builder@v4.3.0
  
